services:
  database:
    image: postgres
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=mypassword
      - POSTGRES_DB=chat-engine
    ports:
      - "5432:5432"
  redis:
    image: redis
    ports:
      - "6379:6379"
  qdrant:
    image: qdrant/qdrant
    ports:
      - "6333:6333"
